
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 585768155863.dkr.ecr.us-east-1.amazonaws.com/authapp:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: authapp-secret
                key: MONGO_URI

          - name: MONGO_DB
            valueFrom:
              secretKeyRef:
                name: authapp-secret
                key: MONGO_DB

          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: authapp-secret
                key: JWT_SECRET

