apiVersion: v1 # API base para manejar Secrets
kind: Secret # Tipo de recurso: un Secret almacena información sensible
metadata:
  name: authapp-secret # Nombre del Secret
type: Opaque # Tipo de Secret genérico (texto plano codificado en base64)
stringData:
  MONGO_URI: mongodb+srv://Osvaldevops:Osvaldo1@cluster0.c0pfm.mongodb.net/appDB?retryWrites=true&w=majority&appName=Cluster0
  MONGO_DB: appDB
  JWT_SECRET: "secretkeyosvaldevopsproyectssacvoigatestingasddffsecretkeyosvaldevopsproyectssacvoigatestingasddff"